name = "Preprocessing_Pipeline_JuML"
uuid = "08ca93ca-ffbd-40e9-9748-42c73b2bdb32"
authors = ["Michelle Kappl <michelle.kappl@gmail.com>", "Leon Schreiber <leonschreiber96@gmail.com>", "Marike Voßbeck <Marike_vossbeck@posteo.de>"]
version = "1.0.0-DEV"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StopWords = "35248bf2-58a5-46a0-9b1d-c0a73a50a107"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"

[compat]
LiveServer = "1"
Documenter = "1.8"
Revise = "3"
julia = "1.10"
